name: GymBook
description: GymBook services.

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  back_button_interceptor: ^6.0.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  file_picker: ^4.0.3
  firebase: ^9.0.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.10.2
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.3
  firestore_search: ^0.1.7
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.0
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.2.0
  flutter_native_splash: ^2.2.3+1
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.2.0
  flutter_speed_dial: ^6.0.0
  flutter_windowmanager: ^0.2.0
  flutterfire_ui: any
  gender_picker: ^1.1.0
  get: ^4.6.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: any
  introduction_screen: ^3.0.2
  marquee: ^2.2.0
  page_transition: ^2.0.4
  path: ^1.8.0
  provider: ^6.0.1
  scoped_model: ^1.1.0
  simple_animations: ^2.3.0
  syncfusion_flutter_calendar: ^20.2.36
  table_calendar: ^3.0.6
  timeago: any
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/splash_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1F1F1F"
  image: "assets/app_icon_transparent.png"
  android: true
  ios: true

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

  assets:
    - assets/images/
    - assets/images/introduction/vector-person.png
    - assets/images/introduction/vector-lupa.png
    - assets/images/facebook-logo.png
    - assets/images/google-logo.png
    - assets/images/apple-logo.png
    - assets/images/intro_ejemplo1.png
    - assets/images/intro_ejemplo2.png
    - assets/images/introduction/intro_entren_1.jpg
    - assets/images/introduction/intro_entren_2.jpg
    - assets/images/introduction/intro_entren_3.jpg
    - assets/images/introduction/intro_entren_4.jpg
    - assets/AtoZ/letter-a.png
    - assets/AtoZ/letter-b.png
    - assets/AtoZ/letter-c.png
    - assets/AtoZ/letter-d.png
    - assets/AtoZ/letter-e.png
    - assets/AtoZ/letter-f.png
    - assets/AtoZ/letter-g.png
    - assets/AtoZ/letter-h.png
    - assets/AtoZ/letter-i.png
    - assets/AtoZ/letter-j.png
    - assets/AtoZ/letter-k.png
    - assets/AtoZ/letter-l.png
    - assets/AtoZ/letter-m.png
    - assets/AtoZ/letter-n.png
    - assets/AtoZ/letter-o.png
    - assets/AtoZ/letter-p.png
    - assets/AtoZ/letter-q.png
    - assets/AtoZ/letter-r.png
    - assets/AtoZ/letter-s.png
    - assets/AtoZ/letter-t.png
    - assets/AtoZ/letter-u.png
    - assets/AtoZ/letter-v.png
    - assets/AtoZ/letter-w.png
    - assets/AtoZ/letter-x.png
    - assets/AtoZ/letter-y.png
    - assets/AtoZ/letter-z.png
    - assets/app_icon_transparent.png
    - assets/splash_icon.png
    - assets/app_icon_white.png
    - assets/icons_ejercicios/abdomen.png
    - assets/icons_ejercicios/brazo.png
    - assets/icons_ejercicios/espalda.png
    - assets/icons_ejercicios/pecho.png
    - assets/icons_ejercicios/pierna.png
    - assets/icons_ejercicios/hombros.png
    - assets/icons_ejercicios/gluteos.png
